language: node_js
node_js:
  - "node"
before_script: 
  - npm install -g nyc
  - npm install -g coveralls
  - cd adt-pulse-mqtt
script:
  - npm install 
  - npm test
after_success:
  - nyc report --reporter=text-lcov | coveralls