# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        #node-version: [12.x, 14.x, 15.x, 16.x]
        #node-version: [14.x, 16.x, 18.x, 20.x]
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g nyc
    - run: npm install -g coveralls
    - run: npm ci #install
      working-directory: adt-pulse-mqtt
    - run: npm test
      working-directory: adt-pulse-mqtt
    - run: npx nyc --reporter=lcov npm test
      working-directory: adt-pulse-mqtt
    - run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --project-token ${{ secrets.CODACY_PROJECT_TOKEN }}
      working-directory: adt-pulse-mqtt
